In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score

%matplotlib inline

In [2]:
# Load the dataset
df = pd.read_excel(r'C:\Users\sg_cl\Desktop\masters subjects\DSRT 736\Fraud Dataset\credit_card_transactions.xlsx')

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
print (df.head())

   User  Card  Year  Month  Day      Time  Amount           Use Chip  \
0     0     0  2002      9    1  06:21:00  134.09  Swipe Transaction   
1     0     0  2002      9    1  06:42:00   38.48  Swipe Transaction   
2     0     0  2002      9    2  06:22:00  120.34  Swipe Transaction   
3     0     0  2002      9    2  17:45:00  128.95  Swipe Transaction   
4     0     0  2002      9    3  06:23:00  104.71  Swipe Transaction   

         Merchant Name  Merchant City Merchant State      Zip   MCC Errors?  \
0  3527213246127869952       La Verne             CA  91750.0  5300     NaN   
1  -727612092139916032  Monterey Park             CA  91754.0  5411     NaN   
2  -727612092139916032  Monterey Park             CA  91754.0  5411     NaN   
3  3414527459579100160  Monterey Park             CA  91754.0  5651     NaN   
4  5817218446178729984       La Verne             CA  91750.0  5912     NaN   

  Is Fraud?  
0        No  
1        No  
2        No  
3        No  
4        No  


In [5]:
df = df.drop('Merchant City', axis=1)
df = df.drop('Zip', axis=1)
df = df.drop('Errors?', axis=1)
df = df.drop('Time', axis=1)

In [6]:

print(df.head())

   User  Card  Year  Month  Day  Amount           Use Chip  \
0     0     0  2002      9    1  134.09  Swipe Transaction   
1     0     0  2002      9    1   38.48  Swipe Transaction   
2     0     0  2002      9    2  120.34  Swipe Transaction   
3     0     0  2002      9    2  128.95  Swipe Transaction   
4     0     0  2002      9    3  104.71  Swipe Transaction   

         Merchant Name Merchant State   MCC Is Fraud?  
0  3527213246127869952             CA  5300        No  
1  -727612092139916032             CA  5411        No  
2  -727612092139916032             CA  5411        No  
3  3414527459579100160             CA  5651        No  
4  5817218446178729984             CA  5912        No  


In [7]:
#Data pre processing String values to Int values
print(df['Use Chip'].unique())

df['Use Chip']
enc = preprocessing.LabelEncoder()
enc.fit(df['Use Chip'])
df['Use Chip'] = enc.transform(df['Use Chip'])

print(df['Use Chip'].unique())


#Data pre processing String values to Int values
print(df['Merchant State'].unique())

df['Merchant State']
enc = preprocessing.LabelEncoder()
enc.fit(df['Merchant State'])
df['Merchant State'] = enc.transform(df['Merchant State'])

print(df['Merchant State'].unique())

['Swipe Transaction' 'Online Transaction' 'Chip Transaction']
[2 1 0]
['CA' nan 'NE' 'IL' 'MO' 'Switzerland' 'IA' 'TX' 'Estonia' 'NJ' 'NV' 'NY'
 'Japan' 'AZ' 'UT' 'FL' 'MI' 'Mexico' 'WA' 'OH' 'Dominican Republic' 'NM'
 'China' 'SC' 'AK' 'PA' 'VA' 'Portugal' 'HI' 'CT' 'MA' 'MN' 'CO' 'Italy'
 'GA' 'Philippines' 'Jamaica' 'AR' 'Canada' 'OR' 'WI' 'NC' 'France' 'WV'
 'Norway' 'ME' 'NH' 'VT' 'MD' 'AL' 'KY' 'TN' 'MS' 'New Zealand'
 'Netherlands' 'KS' 'ND' 'DC' 'Sierra Leone' 'Haiti' 'MT' 'South Korea'
 'Spain' 'OK' 'Algeria' 'Egypt' 'WY' 'ID' 'Indonesia' 'RI'
 'United Kingdom' 'Colombia' 'South Africa' 'IN' 'The Bahamas' 'Singapore'
 'Pakistan' 'Malaysia' 'Mongolia' 'Israel' 'Hong Kong' 'Guatemala' 'Peru'
 'Thailand' 'Sweden' 'Taiwan' 'LA' 'Germany' 'Czech Republic' 'India'
 'Poland' 'DE' 'Costa Rica' 'Denmark' 'Bangladesh' 'Macedonia' 'Nigeria'
 'SD' 'Tuvalu' 'Ireland' 'Vatican City' 'Lithuania' 'Papua New Guinea'
 'Belgium' 'Benin' 'Croatia' 'Saudi Arabia' 'Latvia' 'Austria' 'Slovenia'
 'Tu

In [8]:
#Data pre processing String values to Int values
print(df['Is Fraud?'].unique())
y = df['Is Fraud?']
enc = preprocessing.LabelEncoder()
enc.fit(y)
y = enc.transform(y)
print(y)


# Separate features (X) and labels (y)
X = df.drop('Is Fraud?', axis=1)
print(X.head())
print(y)

['No' 'Yes']
[0 0 0 ... 0 0 0]
   User  Card  Year  Month  Day  Amount  Use Chip        Merchant Name  \
0     0     0  2002      9    1  134.09         2  3527213246127869952   
1     0     0  2002      9    1   38.48         2  -727612092139916032   
2     0     0  2002      9    2  120.34         2  -727612092139916032   
3     0     0  2002      9    2  128.95         2  3414527459579100160   
4     0     0  2002      9    3  104.71         2  5817218446178729984   

   Merchant State   MCC  
0              11  5300  
1              11  5411  
2              11  5411  
3              11  5651  
4              11  5912  
[0 0 0 ... 0 0 0]


In [9]:
type(y)
y[208]

0

In [10]:
print("Missing values:", df.isnull().sum())

Missing values: User              0
Card              0
Year              0
Month             0
Day               0
Amount            0
Use Chip          0
Merchant Name     0
Merchant State    0
MCC               0
Is Fraud?         0
dtype: int64


In [11]:
# Split the dataset into training, validation, and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size=0.5, stratify=y_test, random_state=42)

In [12]:
# Print the shapes of the resulting subsets
print("Training set shape:", X_train.shape, y_train.shape)
print("Validation set shape:", X_val.shape, y_val.shape)
print("Test set shape:", X_test.shape, y_test.shape)

Training set shape: (734002, 10) (734002,)
Validation set shape: (157286, 10) (157286,)
Test set shape: (157287, 10) (157287,)


In [13]:
# Create a linear regression model
model = LinearRegression()

In [14]:
# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [15]:
# Make predictions on the test set
y_pred = model.predict(X_test)

In [16]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.0010034642517910719


In [19]:
print(y_pred)
# Set a threshold
threshold = 0.1

# Convert predictions to binary classes based on the threshold
y_pred_binary = [1 if val >= threshold else 0 for val in y_pred]

# Print the binary predictions
print("Binary Predictions:", y_pred_binary)

[0.00110654 0.00122056 0.00096036 ... 0.00112764 0.00098799 0.0011019 ]
Binary Predictions: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [20]:
accuracy = accuracy_score(y_test, y_pred_binary)
print("Accuracy:", accuracy)

Accuracy: 0.9989954668853751


In [21]:
# Select an example for validation (optional)
example_index = 208
example_features = X.iloc[example_index]
example_target = y[example_index]

# Make predictions on the example
example_prediction = model.predict([example_features])

# Compare with actual value
print("Example features:", example_features)
print("Example target:", example_target)
print("Example prediction:", example_prediction)

# Calculate mean squared error on the test set (optional)
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)
print(y_pred)

Example features: User              0.000000e+00
Card              0.000000e+00
Year              2.002000e+03
Month             1.100000e+01
Day               1.600000e+01
Amount            5.974000e+01
Use Chip          2.000000e+00
Merchant Name     4.055257e+18
Merchant State    1.100000e+01
MCC               7.538000e+03
Name: 208, dtype: float64
Example target: 0
Example prediction: [0.00119346]
Mean Squared Error: 0.0010034642517910719
[0.00110654 0.00122056 0.00096036 ... 0.00112764 0.00098799 0.0011019 ]


C:\Users\sg_cl\anaconda4\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [23]:
counts = y_pred_binary.value_counts()

AttributeError: 'list' object has no attribute 'value_counts'